name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


# -------------------- PACKAGES -------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons
  iconsax: ^0.0.8
  cupertino_icons : ^1.0.2

  # State Management 
  get: ^4.6.5

  #Specific Product 

# -------------------- END PACKAGES -------------------- #



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  # -------------------- LOCAL ASSET -------------------- #

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/
     
  # -------------------- LOCAL FONTS -------------------- #

  fonts:
    - family : Poppins 
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
        - style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
        - weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
        - weight: 500
        - style: italic
        - asset: assets\fonts\Poppins-SemiBold.ttf
        - weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
        - weight: 800
        

